# Generated by Django 6.0.7 on 2026-07-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('user_count', models.PositiveIntegerField(default=0)),
                ('event_count', models.PositiveIntegerField(default=0)),
                ('edited_events', models.PositiveIntegerField(default=0)),
                ('cancelled_events', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('details', models.TextField(blank=True, null=True)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
