# Generated by Django 6.0.7 on 2026-07-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botstatistics',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
