# Generated by Codex on 2026-07-13

from django.db import migrations, models


def move_scheduled_appointments_to_pending(apps, schema_editor):
    appointment = apps.get_model("calendar_bot", "Appointment")
    appointment.objects.filter(status="Scheduled").update(status="pending")


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_bot", "0003_appointment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={"ordering": ["appointment_date", "appointment_time"]},
        ),
        migrations.AddField(
            model_name="appointment",
            name="duration_minutes",
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.RunPython(
            move_scheduled_appointments_to_pending,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидание"),
                    ("confirmed", "Подтверждено"),
                    ("cancelled", "Отменено"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["user_id", "appointment_date", "status"],
                name="calendar_bo_user_id_3d85cf_idx",
            ),
        ),
    ]
