# Generated by Codex on 2026-07-13

import django.db.models.deletion
from django.db import migrations, models


def copy_legacy_registered_users(apps, schema_editor):
    telegram_user_model = apps.get_model("calendar_bot", "TelegramUser")

    with schema_editor.connection.cursor() as cursor:
        existing_tables = schema_editor.connection.introspection.table_names(cursor)
        if "users" not in existing_tables:
            return

        cursor.execute("SELECT id, name FROM users")
        for telegram_id, name in cursor.fetchall():
            telegram_user_model.objects.get_or_create(
                telegram_id=telegram_id,
                defaults={"name": name or ""},
            )


def create_users_for_existing_events(apps, schema_editor):
    event_model = apps.get_model("calendar_bot", "Event")
    telegram_user_model = apps.get_model("calendar_bot", "TelegramUser")

    for event in event_model.objects.filter(owner__isnull=True):
        user, _ = telegram_user_model.objects.get_or_create(
            telegram_id=event.user_id,
            defaults={"name": ""},
        )
        event.owner_id = user.id
        event.save(update_fields=["owner"])


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_bot", "0004_update_appointment_statuses"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_id", models.BigIntegerField(unique=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("events_created", models.PositiveIntegerField(default=0)),
                ("events_edited", models.PositiveIntegerField(default=0)),
                ("events_cancelled", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["telegram_id"],
            },
        ),
        migrations.AlterField(
            model_name="event",
            name="user_id",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="user_id",
            field=models.BigIntegerField(),
        ),
        migrations.RunPython(
            copy_legacy_registered_users,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name="event",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="calendar_bot.telegramuser",
            ),
        ),
        migrations.RunPython(
            create_users_for_existing_events,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="event",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="calendar_bot.telegramuser",
            ),
        ),
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["date", "time", "id"]},
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["user_id", "date"],
                name="calendar_bo_user_id_9c57b4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["owner", "date"],
                name="calendar_bo_owner_i_ef3c11_idx",
            ),
        ),
    ]
