# Generated by Codex on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_bot", "0005_telegram_user_event_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["owner", "is_public", "date"],
                name="calendar_bo_owner_i_2f7a42_idx",
            ),
        ),
    ]
